# Generated by Django 4.1.5 on 2023-01-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
