# Generated by Django 4.1.5 on 2023-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postIt', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='creator',
            field=models.CharField(max_length=20),
        ),
    ]
