# Generated by Django 4.1.5 on 2023-01-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postIt', '0004_alter_notes_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='creator',
            field=models.CharField(max_length=280),
        ),
    ]
